apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproject
  labels:
    app: capstoneproject
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstoneproject
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstoneproject
    spec:
      containers:
      - image: ultraviolentlight/deployment_nginx_kubernetes:latest
        imagePullPolicy: Always
        name: capstoneproject
        ports:
        - containerPort: 80
          protocol: TCP

---
  apiVersion: v1
  kind: Service
  metadata:
    name: capstoneproject
  spec:
    type: LoadBalancer
    selector:
      app: capstoneproject
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80
      - name: https
        protocol: TCP
        port: 443
        targetPort: 443